#pragma once

#include <limits.h>
#include <stddef.h>
#include <stdint.h>

#include "../../../Core/Error/Status.h"

#include "../Math.space"

#define MATH_ARITHMETIC_ADD_PROTOTYPE(TYPE, SUFFIX)                  \
  inline static OPSTATUS ARITHMETIC_TYPED_FUNC(Add, SUFFIX)(             \
      TYPE a, TYPE b, TYPE *result)

#define MATH_ARITHMETIC_SUB_PROTOTYPE(TYPE, SUFFIX)                  \
  inline static OPSTATUS ARITHMETIC_TYPED_FUNC(Sub, SUFFIX)(             \
      TYPE a, TYPE b, TYPE *result)

#define MATH_ARITHMETIC_MUL_PROTOTYPE(TYPE, SUFFIX)                  \
  inline static OPSTATUS ARITHMETIC_TYPED_FUNC(Mul, SUFFIX)(             \
      TYPE a, TYPE b, TYPE *result)

#define MATH_ARITHMETIC_DIV_PROTOTYPE(TYPE, SUFFIX)                  \
  inline static OPSTATUS ARITHMETIC_TYPED_FUNC(Div, SUFFIX)(             \
      TYPE a, TYPE b, TYPE *result)

#define MATH_ARITHMETIC_MOD_PROTOTYPE(TYPE, SUFFIX)                  \
  inline static OPSTATUS ARITHMETIC_TYPED_FUNC(Mod, SUFFIX)(             \
      TYPE a, TYPE b, TYPE *result)

#include "Impl/Basic.impl"

#define MATH_ARITHMETIC_BASIC_SIGNED_INSTANTIATE(                             \
    TYPE, SUFFIX, MINIMUM, MAXIMUM)                                           \
  MATH_ARITHMETIC_ADD_SIGNED_IMPLEMENT(TYPE, SUFFIX, MINIMUM, MAXIMUM)        \
  MATH_ARITHMETIC_SUB_SIGNED_IMPLEMENT(TYPE, SUFFIX, MINIMUM, MAXIMUM)        \
  MATH_ARITHMETIC_MUL_SIGNED_IMPLEMENT(TYPE, SUFFIX, MINIMUM, MAXIMUM)        \
  MATH_ARITHMETIC_DIV_SIGNED_IMPLEMENT(TYPE, SUFFIX, MINIMUM)                 \
  MATH_ARITHMETIC_MOD_SIGNED_IMPLEMENT(TYPE, SUFFIX, MINIMUM)

#define MATH_ARITHMETIC_BASIC_UNSIGNED_INSTANTIATE(                           \
    TYPE, SUFFIX, MAXIMUM)                                                    \
  MATH_ARITHMETIC_ADD_UNSIGNED_IMPLEMENT(TYPE, SUFFIX, MAXIMUM)               \
  MATH_ARITHMETIC_SUB_UNSIGNED_IMPLEMENT(TYPE, SUFFIX)                        \
  MATH_ARITHMETIC_MUL_UNSIGNED_IMPLEMENT(TYPE, SUFFIX, MAXIMUM)               \
  MATH_ARITHMETIC_DIV_UNSIGNED_IMPLEMENT(TYPE, SUFFIX)                        \
  MATH_ARITHMETIC_MOD_UNSIGNED_IMPLEMENT(TYPE, SUFFIX)

MATH_ARITHMETIC_BASIC_SIGNED_INSTANTIATE(
    int8_t, I8, INT8_MIN, INT8_MAX)

MATH_ARITHMETIC_BASIC_SIGNED_INSTANTIATE(
    int16_t, I16, INT16_MIN, INT16_MAX)

MATH_ARITHMETIC_BASIC_SIGNED_INSTANTIATE(
    int32_t, I32, INT32_MIN, INT32_MAX)

MATH_ARITHMETIC_BASIC_SIGNED_INSTANTIATE(
    int64_t, I64, INT64_MIN, INT64_MAX)

MATH_ARITHMETIC_BASIC_UNSIGNED_INSTANTIATE(
    uint8_t, U8, UINT8_MAX)

MATH_ARITHMETIC_BASIC_UNSIGNED_INSTANTIATE(
    uint16_t, U16, UINT16_MAX)

MATH_ARITHMETIC_BASIC_UNSIGNED_INSTANTIATE(
    uint32_t, U32, UINT32_MAX)

MATH_ARITHMETIC_BASIC_UNSIGNED_INSTANTIATE(
    uint64_t, U64, UINT64_MAX)

/* EOF */
