#pragma once

#include <limits.h>
#include <stdint.h>

#include "../../../Core/Memory/Swap.h"

#include "Basic.h"
#include "../Value/Clamp.h"
#include "../Value/Between.h"
#include "../Math.space"

#define MATH_ARITHMETIC_CLAMP_ADD_PROTOTYPE(TYPE, SUFFIX)            \
  inline static TYPE ARITHMETIC_TYPED_FUNC(ClampAdd, SUFFIX)(            \
      TYPE a, TYPE b, TYPE minimum, TYPE maximum)

#define MATH_ARITHMETIC_CLAMP_SUB_PROTOTYPE(TYPE, SUFFIX)            \
  inline static TYPE ARITHMETIC_TYPED_FUNC(ClampSub, SUFFIX)(            \
      TYPE a, TYPE b, TYPE minimum, TYPE maximum)

#define MATH_ARITHMETIC_CLAMP_MUL_PROTOTYPE(TYPE, SUFFIX)            \
  inline static TYPE ARITHMETIC_TYPED_FUNC(ClampMul, SUFFIX)(            \
      TYPE a, TYPE b, TYPE minimum, TYPE maximum)

#define MATH_ARITHMETIC_SATURATING_ADD_PROTOTYPE(TYPE, SUFFIX)       \
  inline static TYPE ARITHMETIC_TYPED_FUNC(SaturatingAdd, SUFFIX)(       \
      TYPE a, TYPE b)

#define MATH_ARITHMETIC_SATURATING_SUB_PROTOTYPE(TYPE, SUFFIX)       \
  inline static TYPE ARITHMETIC_TYPED_FUNC(SaturatingSub, SUFFIX)(       \
      TYPE a, TYPE b)

#define MATH_ARITHMETIC_SATURATING_MUL_PROTOTYPE(TYPE, SUFFIX)       \
  inline static TYPE ARITHMETIC_TYPED_FUNC(SaturatingMul, SUFFIX)(       \
      TYPE a, TYPE b)

#include "Impl/Clamp.impl"

#define MATH_ARITHMETIC_CLAMP_SIGNED_INSTANTIATE(TYPE, SUFFIX, MINIMUM, MAXIMUM) \
  MATH_ARITHMETIC_CLAMP_ADD_SIGNED_IMPLEMENT(TYPE, SUFFIX)                     \
  MATH_ARITHMETIC_CLAMP_SUB_SIGNED_IMPLEMENT(TYPE, SUFFIX)                     \
  MATH_ARITHMETIC_CLAMP_MUL_SIGNED_IMPLEMENT(TYPE, SUFFIX)                     \
  MATH_ARITHMETIC_SATURATING_IMPLEMENT(TYPE, SUFFIX, MINIMUM, MAXIMUM)

#define MATH_ARITHMETIC_CLAMP_UNSIGNED_INSTANTIATE(TYPE, SUFFIX, MAXIMUM)       \
  MATH_ARITHMETIC_CLAMP_ADD_UNSIGNED_IMPLEMENT(TYPE, SUFFIX)                   \
  MATH_ARITHMETIC_CLAMP_SUB_UNSIGNED_IMPLEMENT(TYPE, SUFFIX)                   \
  MATH_ARITHMETIC_CLAMP_MUL_UNSIGNED_IMPLEMENT(TYPE, SUFFIX)                   \
  MATH_ARITHMETIC_SATURATING_IMPLEMENT(TYPE, SUFFIX, 0, MAXIMUM)

MATH_ARITHMETIC_CLAMP_SIGNED_INSTANTIATE(int8_t, I8, INT8_MIN, INT8_MAX)
MATH_ARITHMETIC_CLAMP_SIGNED_INSTANTIATE(int16_t, I16, INT16_MIN, INT16_MAX)
MATH_ARITHMETIC_CLAMP_SIGNED_INSTANTIATE(int32_t, I32, INT32_MIN, INT32_MAX)
MATH_ARITHMETIC_CLAMP_SIGNED_INSTANTIATE(int64_t, I64, INT64_MIN, INT64_MAX)

MATH_ARITHMETIC_CLAMP_UNSIGNED_INSTANTIATE(uint8_t, U8, UINT8_MAX)
MATH_ARITHMETIC_CLAMP_UNSIGNED_INSTANTIATE(uint16_t, U16, UINT16_MAX)
MATH_ARITHMETIC_CLAMP_UNSIGNED_INSTANTIATE(uint32_t, U32, UINT32_MAX)
MATH_ARITHMETIC_CLAMP_UNSIGNED_INSTANTIATE(uint64_t, U64, UINT64_MAX)

/* EOF */
