#include <assert.h>
#include "../../Cosmeron/Modules/Concurrency/Atomic/Atomic.h"

int main(void) {
  CONCURRENCY_TYPE(TAtomicU32) value = ATOMIC_U32_INIT(1);
  uint32_t expected = 2;

  assert(ATOMIC_FUNC(U32_Load)(&value, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == 1);
  ATOMIC_FUNC(U32_Store)(&value, 2, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST));
  assert(ATOMIC_FUNC(U32_Exchange)(&value, 5, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == 2);
  assert(ATOMIC_FUNC(U32_FetchAdd)(&value, 1, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == 5);
  assert(ATOMIC_FUNC(U32_FetchSub)(&value, 2, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == 6);
  assert(ATOMIC_FUNC(U32_FetchAnd)(&value, 6, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == 4);
  assert(ATOMIC_FUNC(U32_FetchOr)(&value, 1, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == 4);
  assert(ATOMIC_FUNC(U32_FetchXor)(&value, 7, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == 5);
  assert(ATOMIC_FUNC(U32_CompareExchange)(
      &value, &expected, 7, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST),
      CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)));
  assert(ATOMIC_FUNC(U32_Load)(&value, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == 7);

#if CONCURRENCY_HAS_ATOMIC_U64
  {
    CONCURRENCY_TYPE(TAtomicU64) value64 = ATOMIC_U64_INIT(UINT64_C(10));
    uint64_t expected64 = UINT64_C(15);
    assert(ATOMIC_FUNC(U64_Load)(&value64, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == UINT64_C(10));
    ATOMIC_FUNC(U64_Store)(&value64, UINT64_C(11), CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST));
    assert(ATOMIC_FUNC(U64_Exchange)(&value64, UINT64_C(15), CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == UINT64_C(11));
    assert(ATOMIC_FUNC(U64_FetchAdd)(&value64, UINT64_C(2), CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == UINT64_C(15));
    assert(ATOMIC_FUNC(U64_FetchSub)(&value64, UINT64_C(1), CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == UINT64_C(17));
    assert(ATOMIC_FUNC(U64_FetchAnd)(&value64, UINT64_C(0x0F), CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == UINT64_C(16));
    assert(ATOMIC_FUNC(U64_FetchOr)(&value64, UINT64_C(0x10), CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == UINT64_C(0));
    assert(ATOMIC_FUNC(U64_FetchXor)(&value64, UINT64_C(0x01), CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == UINT64_C(16));
    expected64 = UINT64_C(17);
    assert(ATOMIC_FUNC(U64_CompareExchange)(
        &value64, &expected64, UINT64_C(20),
        CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST),
        CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)));
  }
#endif

  {
    CONCURRENCY_TYPE(TAtomicPtr) ptr = ATOMIC_PTR_INIT((uintptr_t)1);
    uintptr_t expectedPtr = (uintptr_t)3;
    assert(ATOMIC_FUNC(Ptr_Load)(&ptr, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == (uintptr_t)1);
    ATOMIC_FUNC(Ptr_Store)(&ptr, (uintptr_t)2, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST));
    assert(ATOMIC_FUNC(Ptr_Exchange)(&ptr, (uintptr_t)3,
                                    CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)) == (uintptr_t)2);
    assert(ATOMIC_FUNC(Ptr_CompareExchange)(
        &ptr, &expectedPtr, (uintptr_t)4,
        CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST),
        CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)));
  }

  {
    CONCURRENCY_TYPE(TAtomicBool) flag = ATOMIC_BOOL_INIT(false);
    assert(!ATOMIC_FUNC(Bool_Load)(&flag, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)));
    ATOMIC_FUNC(Bool_Store)(&flag, true, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST));
    assert(ATOMIC_FUNC(Bool_Exchange)(&flag, false,
                                     CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)));
    assert(!ATOMIC_FUNC(Bool_Load)(&flag, CONCURRENCY_CONST(ATOMIC, MEMORY_ORDER_SEQ_CST)));
  }

  return 0;
}
