#pragma once

#include "../Network.space"

typedef enum NETWORK_TYPE(Error) {
  NETWORK_ERROR_CONST(NONE) = 0,
  NETWORK_ERROR_CONST(TIMEOUT),
  NETWORK_ERROR_CONST(WOULD_BLOCK),
  NETWORK_ERROR_CONST(CONNECTION_REFUSED),
  NETWORK_ERROR_CONST(CONNECTION_RESET),
  NETWORK_ERROR_CONST(CONNECTION_CLOSED),
  NETWORK_ERROR_CONST(CONNECTION_ABORTED),
  NETWORK_ERROR_CONST(NOT_CONNECTED),
  NETWORK_ERROR_CONST(ALREADY_CONNECTED),
  NETWORK_ERROR_CONST(HOST_NOT_FOUND),
  NETWORK_ERROR_CONST(HOST_UNREACHABLE),
  NETWORK_ERROR_CONST(NETWORK_UNREACHABLE),
  NETWORK_ERROR_CONST(ADDRESS_INVALID),
  NETWORK_ERROR_CONST(ADDRESS_IN_USE),
  NETWORK_ERROR_CONST(ADDRESS_UNAVAILABLE),
  NETWORK_ERROR_CONST(PERMISSION_DENIED),
  NETWORK_ERROR_CONST(RESOURCE_EXHAUSTED),
  NETWORK_ERROR_CONST(PROTOCOL_UNSUPPORTED),
  NETWORK_ERROR_CONST(ADDRESS_FAMILY_UNSUPPORTED),
  NETWORK_ERROR_CONST(MESSAGE_TOO_LARGE),
  NETWORK_ERROR_CONST(UNKNOWN)
} TNetwork_Error;
