#pragma once

#include "Compiling.inc"
#include "Operations.h"

#define PP_BOOL(x) PP_OP_CAT2(PP_INTERNAL_BOOL_, x)
#define PP_INTERNAL_BOOL_0 0
#define PP_INTERNAL_BOOL_1 1
#define PP_INTERNAL_BOOL_2 1
#define PP_INTERNAL_BOOL_3 1
#define PP_INTERNAL_BOOL_4 1
#define PP_INTERNAL_BOOL_5 1
#define PP_INTERNAL_BOOL_6 1
#define PP_INTERNAL_BOOL_7 1
#define PP_INTERNAL_BOOL_8 1
#define PP_INTERNAL_BOOL_9 1
#define PP_INTERNAL_BOOL_10 1
#define PP_INTERNAL_BOOL_11 1
#define PP_INTERNAL_BOOL_12 1
#define PP_INTERNAL_BOOL_13 1
#define PP_INTERNAL_BOOL_14 1
#define PP_INTERNAL_BOOL_15 1
#define PP_INTERNAL_BOOL_16 1
#define PP_INTERNAL_BOOL_17 1
#define PP_INTERNAL_BOOL_18 1
#define PP_INTERNAL_BOOL_19 1
#define PP_INTERNAL_BOOL_20 1
#define PP_INTERNAL_BOOL_21 1
#define PP_INTERNAL_BOOL_22 1
#define PP_INTERNAL_BOOL_23 1
#define PP_INTERNAL_BOOL_24 1
#define PP_INTERNAL_BOOL_25 1
#define PP_INTERNAL_BOOL_26 1
#define PP_INTERNAL_BOOL_27 1
#define PP_INTERNAL_BOOL_28 1
#define PP_INTERNAL_BOOL_29 1
#define PP_INTERNAL_BOOL_30 1
#define PP_INTERNAL_BOOL_31 1
#define PP_INTERNAL_BOOL_32 1
#define PP_INTERNAL_BOOL_33 1
#define PP_INTERNAL_BOOL_34 1
#define PP_INTERNAL_BOOL_35 1
#define PP_INTERNAL_BOOL_36 1
#define PP_INTERNAL_BOOL_37 1
#define PP_INTERNAL_BOOL_38 1
#define PP_INTERNAL_BOOL_39 1
#define PP_INTERNAL_BOOL_40 1
#define PP_INTERNAL_BOOL_41 1
#define PP_INTERNAL_BOOL_42 1
#define PP_INTERNAL_BOOL_43 1
#define PP_INTERNAL_BOOL_44 1
#define PP_INTERNAL_BOOL_45 1
#define PP_INTERNAL_BOOL_46 1
#define PP_INTERNAL_BOOL_47 1
#define PP_INTERNAL_BOOL_48 1
#define PP_INTERNAL_BOOL_49 1
#define PP_INTERNAL_BOOL_50 1
#define PP_INTERNAL_BOOL_51 1
#define PP_INTERNAL_BOOL_52 1
#define PP_INTERNAL_BOOL_53 1
#define PP_INTERNAL_BOOL_54 1
#define PP_INTERNAL_BOOL_55 1
#define PP_INTERNAL_BOOL_56 1
#define PP_INTERNAL_BOOL_57 1
#define PP_INTERNAL_BOOL_58 1
#define PP_INTERNAL_BOOL_59 1
#define PP_INTERNAL_BOOL_60 1
#define PP_INTERNAL_BOOL_61 1
#define PP_INTERNAL_BOOL_62 1
#define PP_INTERNAL_BOOL_63 1
#define PP_INTERNAL_BOOL_64 1
#define PP_INTERNAL_BOOL_65 1
#define PP_INTERNAL_BOOL_66 1
#define PP_INTERNAL_BOOL_67 1
#define PP_INTERNAL_BOOL_68 1
#define PP_INTERNAL_BOOL_69 1
#define PP_INTERNAL_BOOL_70 1
#define PP_INTERNAL_BOOL_71 1
#define PP_INTERNAL_BOOL_72 1
#define PP_INTERNAL_BOOL_73 1
#define PP_INTERNAL_BOOL_74 1
#define PP_INTERNAL_BOOL_75 1
#define PP_INTERNAL_BOOL_76 1
#define PP_INTERNAL_BOOL_77 1
#define PP_INTERNAL_BOOL_78 1
#define PP_INTERNAL_BOOL_79 1
#define PP_INTERNAL_BOOL_80 1
#define PP_INTERNAL_BOOL_81 1
#define PP_INTERNAL_BOOL_82 1
#define PP_INTERNAL_BOOL_83 1
#define PP_INTERNAL_BOOL_84 1
#define PP_INTERNAL_BOOL_85 1
#define PP_INTERNAL_BOOL_86 1
#define PP_INTERNAL_BOOL_87 1
#define PP_INTERNAL_BOOL_88 1
#define PP_INTERNAL_BOOL_89 1
#define PP_INTERNAL_BOOL_90 1
#define PP_INTERNAL_BOOL_91 1
#define PP_INTERNAL_BOOL_92 1
#define PP_INTERNAL_BOOL_93 1
#define PP_INTERNAL_BOOL_94 1
#define PP_INTERNAL_BOOL_95 1
#define PP_INTERNAL_BOOL_96 1
#define PP_INTERNAL_BOOL_97 1
#define PP_INTERNAL_BOOL_98 1
#define PP_INTERNAL_BOOL_99 1
#define PP_INTERNAL_BOOL_100 1

#define PP_BOOL_NOT(x) PP_OP_CAT2(PP_INTERNAL_NOT_, PP_BOOL(x))
#define PP_INTERNAL_NOT_0 1
#define PP_INTERNAL_NOT_1 0

#define PP_BOOL_IF(cond) PP_OP_CAT2(PP_INTERNAL_IF_, PP_BOOL(cond))
#define PP_INTERNAL_IF_0(...)
#define PP_INTERNAL_IF_1(...) __VA_ARGS__

#define PP_BOOL_IF_ELSE(cond) PP_OP_CAT2(PP_INTERNAL_IF_ELSE_, PP_BOOL(cond))
#define PP_INTERNAL_IF_ELSE_0(trueBranch) PP_INTERNAL_IF_ELSE_0_ELSE
#define PP_INTERNAL_IF_ELSE_0_ELSE(falseBranch) falseBranch
#define PP_INTERNAL_IF_ELSE_1(trueBranch) trueBranch PP_INTERNAL_IF_ELSE_1_ELSE
#define PP_INTERNAL_IF_ELSE_1_ELSE(falseBranch)

#define PP_BOOL_AND(a, b) PP_OP_CAT2(PP_INTERNAL_AND_, PP_OP_CAT2(PP_BOOL(a), PP_BOOL(b)))
#define PP_INTERNAL_AND_00 0
#define PP_INTERNAL_AND_01 0
#define PP_INTERNAL_AND_10 0
#define PP_INTERNAL_AND_11 1

#define PP_BOOL_OR(a, b) PP_OP_CAT2(PP_INTERNAL_OR_, PP_OP_CAT2(PP_BOOL(a), PP_BOOL(b)))
#define PP_INTERNAL_OR_00 0
#define PP_INTERNAL_OR_01 1
#define PP_INTERNAL_OR_10 1
#define PP_INTERNAL_OR_11 1

#define PP_BOOL_XOR(a, b) PP_OP_CAT2(PP_INTERNAL_XOR_, PP_OP_CAT2(PP_BOOL(a), PP_BOOL(b)))
#define PP_INTERNAL_XOR_00 0
#define PP_INTERNAL_XOR_01 1
#define PP_INTERNAL_XOR_10 1
#define PP_INTERNAL_XOR_11 0
/* EOF */
