#pragma once

#include "Compiling.inc"
#include "Arguments.h"
#include "Operations.h"

#define PP_FOREACH(macro, ...)                                                \
  PP_OP_CAT2(PP_FOREACH_, PP_ARG_COUNT(__VA_ARGS__))(macro, __VA_ARGS__)

#define PP_FOREACH_1(macro, a1) macro(a1)
#define PP_FOREACH_2(macro, a1, ...) macro(a1) PP_FOREACH_1(macro, __VA_ARGS__)
#define PP_FOREACH_3(macro, a1, ...) macro(a1) PP_FOREACH_2(macro, __VA_ARGS__)
#define PP_FOREACH_4(macro, a1, ...) macro(a1) PP_FOREACH_3(macro, __VA_ARGS__)
#define PP_FOREACH_5(macro, a1, ...) macro(a1) PP_FOREACH_4(macro, __VA_ARGS__)
#define PP_FOREACH_6(macro, a1, ...) macro(a1) PP_FOREACH_5(macro, __VA_ARGS__)
#define PP_FOREACH_7(macro, a1, ...) macro(a1) PP_FOREACH_6(macro, __VA_ARGS__)
#define PP_FOREACH_8(macro, a1, ...) macro(a1) PP_FOREACH_7(macro, __VA_ARGS__)
#define PP_FOREACH_9(macro, a1, ...) macro(a1) PP_FOREACH_8(macro, __VA_ARGS__)
#define PP_FOREACH_10(macro, a1, ...) macro(a1) PP_FOREACH_9(macro, __VA_ARGS__)
#define PP_FOREACH_11(macro, a1, ...) macro(a1) PP_FOREACH_10(macro, __VA_ARGS__)
#define PP_FOREACH_12(macro, a1, ...) macro(a1) PP_FOREACH_11(macro, __VA_ARGS__)
#define PP_FOREACH_13(macro, a1, ...) macro(a1) PP_FOREACH_12(macro, __VA_ARGS__)
#define PP_FOREACH_14(macro, a1, ...) macro(a1) PP_FOREACH_13(macro, __VA_ARGS__)
#define PP_FOREACH_15(macro, a1, ...) macro(a1) PP_FOREACH_14(macro, __VA_ARGS__)
#define PP_FOREACH_16(macro, a1, ...) macro(a1) PP_FOREACH_15(macro, __VA_ARGS__)
#define PP_FOREACH_17(macro, a1, ...) macro(a1) PP_FOREACH_16(macro, __VA_ARGS__)
#define PP_FOREACH_18(macro, a1, ...) macro(a1) PP_FOREACH_17(macro, __VA_ARGS__)
#define PP_FOREACH_19(macro, a1, ...) macro(a1) PP_FOREACH_18(macro, __VA_ARGS__)
#define PP_FOREACH_20(macro, a1, ...) macro(a1) PP_FOREACH_19(macro, __VA_ARGS__)
#define PP_FOREACH_21(macro, a1, ...) macro(a1) PP_FOREACH_20(macro, __VA_ARGS__)
#define PP_FOREACH_22(macro, a1, ...) macro(a1) PP_FOREACH_21(macro, __VA_ARGS__)
#define PP_FOREACH_23(macro, a1, ...) macro(a1) PP_FOREACH_22(macro, __VA_ARGS__)
#define PP_FOREACH_24(macro, a1, ...) macro(a1) PP_FOREACH_23(macro, __VA_ARGS__)
#define PP_FOREACH_25(macro, a1, ...) macro(a1) PP_FOREACH_24(macro, __VA_ARGS__)
#define PP_FOREACH_26(macro, a1, ...) macro(a1) PP_FOREACH_25(macro, __VA_ARGS__)
#define PP_FOREACH_27(macro, a1, ...) macro(a1) PP_FOREACH_26(macro, __VA_ARGS__)
#define PP_FOREACH_28(macro, a1, ...) macro(a1) PP_FOREACH_27(macro, __VA_ARGS__)
#define PP_FOREACH_29(macro, a1, ...) macro(a1) PP_FOREACH_28(macro, __VA_ARGS__)
#define PP_FOREACH_30(macro, a1, ...) macro(a1) PP_FOREACH_29(macro, __VA_ARGS__)
#define PP_FOREACH_31(macro, a1, ...) macro(a1) PP_FOREACH_30(macro, __VA_ARGS__)
#define PP_FOREACH_32(macro, a1, ...) macro(a1) PP_FOREACH_31(macro, __VA_ARGS__)
#define PP_FOREACH_33(macro, a1, ...) macro(a1) PP_FOREACH_32(macro, __VA_ARGS__)
#define PP_FOREACH_34(macro, a1, ...) macro(a1) PP_FOREACH_33(macro, __VA_ARGS__)
#define PP_FOREACH_35(macro, a1, ...) macro(a1) PP_FOREACH_34(macro, __VA_ARGS__)
#define PP_FOREACH_36(macro, a1, ...) macro(a1) PP_FOREACH_35(macro, __VA_ARGS__)
#define PP_FOREACH_37(macro, a1, ...) macro(a1) PP_FOREACH_36(macro, __VA_ARGS__)
#define PP_FOREACH_38(macro, a1, ...) macro(a1) PP_FOREACH_37(macro, __VA_ARGS__)
#define PP_FOREACH_39(macro, a1, ...) macro(a1) PP_FOREACH_38(macro, __VA_ARGS__)
#define PP_FOREACH_40(macro, a1, ...) macro(a1) PP_FOREACH_39(macro, __VA_ARGS__)
#define PP_FOREACH_41(macro, a1, ...) macro(a1) PP_FOREACH_40(macro, __VA_ARGS__)
#define PP_FOREACH_42(macro, a1, ...) macro(a1) PP_FOREACH_41(macro, __VA_ARGS__)
#define PP_FOREACH_43(macro, a1, ...) macro(a1) PP_FOREACH_42(macro, __VA_ARGS__)
#define PP_FOREACH_44(macro, a1, ...) macro(a1) PP_FOREACH_43(macro, __VA_ARGS__)
#define PP_FOREACH_45(macro, a1, ...) macro(a1) PP_FOREACH_44(macro, __VA_ARGS__)
#define PP_FOREACH_46(macro, a1, ...) macro(a1) PP_FOREACH_45(macro, __VA_ARGS__)
#define PP_FOREACH_47(macro, a1, ...) macro(a1) PP_FOREACH_46(macro, __VA_ARGS__)
#define PP_FOREACH_48(macro, a1, ...) macro(a1) PP_FOREACH_47(macro, __VA_ARGS__)
#define PP_FOREACH_49(macro, a1, ...) macro(a1) PP_FOREACH_48(macro, __VA_ARGS__)
#define PP_FOREACH_50(macro, a1, ...) macro(a1) PP_FOREACH_49(macro, __VA_ARGS__)
#define PP_FOREACH_51(macro, a1, ...) macro(a1) PP_FOREACH_50(macro, __VA_ARGS__)
#define PP_FOREACH_52(macro, a1, ...) macro(a1) PP_FOREACH_51(macro, __VA_ARGS__)
#define PP_FOREACH_53(macro, a1, ...) macro(a1) PP_FOREACH_52(macro, __VA_ARGS__)
#define PP_FOREACH_54(macro, a1, ...) macro(a1) PP_FOREACH_53(macro, __VA_ARGS__)
#define PP_FOREACH_55(macro, a1, ...) macro(a1) PP_FOREACH_54(macro, __VA_ARGS__)
#define PP_FOREACH_56(macro, a1, ...) macro(a1) PP_FOREACH_55(macro, __VA_ARGS__)
#define PP_FOREACH_57(macro, a1, ...) macro(a1) PP_FOREACH_56(macro, __VA_ARGS__)
#define PP_FOREACH_58(macro, a1, ...) macro(a1) PP_FOREACH_57(macro, __VA_ARGS__)
#define PP_FOREACH_59(macro, a1, ...) macro(a1) PP_FOREACH_58(macro, __VA_ARGS__)
#define PP_FOREACH_60(macro, a1, ...) macro(a1) PP_FOREACH_59(macro, __VA_ARGS__)
#define PP_FOREACH_61(macro, a1, ...) macro(a1) PP_FOREACH_60(macro, __VA_ARGS__)
#define PP_FOREACH_62(macro, a1, ...) macro(a1) PP_FOREACH_61(macro, __VA_ARGS__)
#define PP_FOREACH_63(macro, a1, ...) macro(a1) PP_FOREACH_62(macro, __VA_ARGS__)
#define PP_FOREACH_64(macro, a1, ...) macro(a1) PP_FOREACH_63(macro, __VA_ARGS__)
#define PP_FOREACH_65(macro, a1, ...) macro(a1) PP_FOREACH_64(macro, __VA_ARGS__)
#define PP_FOREACH_66(macro, a1, ...) macro(a1) PP_FOREACH_65(macro, __VA_ARGS__)
#define PP_FOREACH_67(macro, a1, ...) macro(a1) PP_FOREACH_66(macro, __VA_ARGS__)
#define PP_FOREACH_68(macro, a1, ...) macro(a1) PP_FOREACH_67(macro, __VA_ARGS__)
#define PP_FOREACH_69(macro, a1, ...) macro(a1) PP_FOREACH_68(macro, __VA_ARGS__)
#define PP_FOREACH_70(macro, a1, ...) macro(a1) PP_FOREACH_69(macro, __VA_ARGS__)
#define PP_FOREACH_71(macro, a1, ...) macro(a1) PP_FOREACH_70(macro, __VA_ARGS__)
#define PP_FOREACH_72(macro, a1, ...) macro(a1) PP_FOREACH_71(macro, __VA_ARGS__)
#define PP_FOREACH_73(macro, a1, ...) macro(a1) PP_FOREACH_72(macro, __VA_ARGS__)
#define PP_FOREACH_74(macro, a1, ...) macro(a1) PP_FOREACH_73(macro, __VA_ARGS__)
#define PP_FOREACH_75(macro, a1, ...) macro(a1) PP_FOREACH_74(macro, __VA_ARGS__)
#define PP_FOREACH_76(macro, a1, ...) macro(a1) PP_FOREACH_75(macro, __VA_ARGS__)
#define PP_FOREACH_77(macro, a1, ...) macro(a1) PP_FOREACH_76(macro, __VA_ARGS__)
#define PP_FOREACH_78(macro, a1, ...) macro(a1) PP_FOREACH_77(macro, __VA_ARGS__)
#define PP_FOREACH_79(macro, a1, ...) macro(a1) PP_FOREACH_78(macro, __VA_ARGS__)
#define PP_FOREACH_80(macro, a1, ...) macro(a1) PP_FOREACH_79(macro, __VA_ARGS__)
#define PP_FOREACH_81(macro, a1, ...) macro(a1) PP_FOREACH_80(macro, __VA_ARGS__)
#define PP_FOREACH_82(macro, a1, ...) macro(a1) PP_FOREACH_81(macro, __VA_ARGS__)
#define PP_FOREACH_83(macro, a1, ...) macro(a1) PP_FOREACH_82(macro, __VA_ARGS__)
#define PP_FOREACH_84(macro, a1, ...) macro(a1) PP_FOREACH_83(macro, __VA_ARGS__)
#define PP_FOREACH_85(macro, a1, ...) macro(a1) PP_FOREACH_84(macro, __VA_ARGS__)
#define PP_FOREACH_86(macro, a1, ...) macro(a1) PP_FOREACH_85(macro, __VA_ARGS__)
#define PP_FOREACH_87(macro, a1, ...) macro(a1) PP_FOREACH_86(macro, __VA_ARGS__)
#define PP_FOREACH_88(macro, a1, ...) macro(a1) PP_FOREACH_87(macro, __VA_ARGS__)
#define PP_FOREACH_89(macro, a1, ...) macro(a1) PP_FOREACH_88(macro, __VA_ARGS__)
#define PP_FOREACH_90(macro, a1, ...) macro(a1) PP_FOREACH_89(macro, __VA_ARGS__)
#define PP_FOREACH_91(macro, a1, ...) macro(a1) PP_FOREACH_90(macro, __VA_ARGS__)
#define PP_FOREACH_92(macro, a1, ...) macro(a1) PP_FOREACH_91(macro, __VA_ARGS__)
#define PP_FOREACH_93(macro, a1, ...) macro(a1) PP_FOREACH_92(macro, __VA_ARGS__)
#define PP_FOREACH_94(macro, a1, ...) macro(a1) PP_FOREACH_93(macro, __VA_ARGS__)
#define PP_FOREACH_95(macro, a1, ...) macro(a1) PP_FOREACH_94(macro, __VA_ARGS__)
#define PP_FOREACH_96(macro, a1, ...) macro(a1) PP_FOREACH_95(macro, __VA_ARGS__)
#define PP_FOREACH_97(macro, a1, ...) macro(a1) PP_FOREACH_96(macro, __VA_ARGS__)
#define PP_FOREACH_98(macro, a1, ...) macro(a1) PP_FOREACH_97(macro, __VA_ARGS__)
#define PP_FOREACH_99(macro, a1, ...) macro(a1) PP_FOREACH_98(macro, __VA_ARGS__)
#define PP_FOREACH_100(macro, a1, ...) macro(a1) PP_FOREACH_99(macro, __VA_ARGS__)
/* EOF */
