#pragma once

#include "../Math.space"

#define MATH_VALUE_CLAMP_PROTOTYPE(TYPE, SUFFIX)                    \
  static inline TYPE VALUE_TYPED_FUNC(Clamp, SUFFIX)(             \
      TYPE value, TYPE minimum, TYPE maximum)

#include "Impl/Clamp.impl"

#define MATH_VALUE_CLAMP_IMPLEMENT_ALL(TYPE, SUFFIX)                           \
  MATH_VALUE_CLAMP_IMPLEMENT(TYPE, SUFFIX)

MATH_VALUE_CLAMP_IMPLEMENT_ALL(int8_t, I8)
MATH_VALUE_CLAMP_IMPLEMENT_ALL(int16_t, I16)
MATH_VALUE_CLAMP_IMPLEMENT_ALL(int32_t, I32)
MATH_VALUE_CLAMP_IMPLEMENT_ALL(int64_t, I64)

MATH_VALUE_CLAMP_IMPLEMENT_ALL(uint8_t, U8)
MATH_VALUE_CLAMP_IMPLEMENT_ALL(uint16_t, U16)
MATH_VALUE_CLAMP_IMPLEMENT_ALL(uint32_t, U32)
MATH_VALUE_CLAMP_IMPLEMENT_ALL(uint64_t, U64)

MATH_VALUE_CLAMP_IMPLEMENT_ALL(float, F32)
MATH_VALUE_CLAMP_IMPLEMENT_ALL(double, F64)
MATH_VALUE_CLAMP_IMPLEMENT_ALL(long double, F128)

/* EOF */
