#pragma once

#include "../Math.space"

#define MATH_VALUE_CLAMP_PROTOTYPE(TYPE, SUFFIX)                    \
  inline static TYPE VALUE_TYPED_FUNC(Clamp, SUFFIX)(             \
      TYPE value, TYPE minimum, TYPE maximum)

#include "Impl/Clamp.impl"

#define MATH_VALUE_CLAMP_INSTANTIATE(TYPE, SUFFIX)                           \
  MATH_VALUE_CLAMP_IMPLEMENT(TYPE, SUFFIX)

MATH_VALUE_CLAMP_INSTANTIATE(int8_t, I8)
MATH_VALUE_CLAMP_INSTANTIATE(int16_t, I16)
MATH_VALUE_CLAMP_INSTANTIATE(int32_t, I32)
MATH_VALUE_CLAMP_INSTANTIATE(int64_t, I64)

MATH_VALUE_CLAMP_INSTANTIATE(uint8_t, U8)
MATH_VALUE_CLAMP_INSTANTIATE(uint16_t, U16)
MATH_VALUE_CLAMP_INSTANTIATE(uint32_t, U32)
MATH_VALUE_CLAMP_INSTANTIATE(uint64_t, U64)

MATH_VALUE_CLAMP_INSTANTIATE(float, F32)
MATH_VALUE_CLAMP_INSTANTIATE(double, F64)
MATH_VALUE_CLAMP_INSTANTIATE(long double, F128)

/* EOF */
